# ==============================================================
# zuul网关
#
# 完整文档查看
# ==============================================================

# 启动端口
server:
  port: 10001

# 配置微服务名称
spring:
  profiles:
    # 测试dev
    active: dev
    # 生产prod
    # active: prod
  application:
    name: zuulserver

# 日志配置dev
logback-logstash-tcp: localhost:9700
logback-application-path: applicationLog/
logback-performance-path: performanceLog/
logback-max-history: 30

