# ==============================================================
# zuul网关
#
# 完整文档查看
# ==============================================================

# 启动端口
server:
  port: 10001

# 配置微服务名称
spring:
  profiles:
    # 测试dev 生产prod
    active: dev
  application:
    name: zuulserver



